spring:
  application:
    name:
      gateway
  cloud:
    gateway:
      routes:
      - id: squadron-service-route
        uri: lb://squadron-service
        predicates:
        - Path=/squadron/**
      - id: commander-service-route
        uri: lb://commander-service
        predicates:
        - Path=/commander/**
      - id: pilot-service-route # need to make this/ update this
        uri: lb://pilot-service
        predicates:
        - Path=/pilot/**
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka