spring:
  application:
   name: pilot-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

server:
 port: 8083
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka