spring:
  application:
   name: squadron-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

springdoc:
  api-docs:
    path: /v3/api-docs/squadron
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
 port: 8081
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka