spring:
  application:
   name: squadron-service
  datasource:
    url: jdbc:mysql://localhost:3306/airforce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
 port: 8081
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka